### PR TITLE
Pay 781

### PR DESCRIPTION
**Pull request by eugene-payfurl**

### CODE REVIEW

**Comment by dcamdupe** [comment]
We're missing one item in this. We need to handle errors being returned from the API. Now that we have a consistent error response, we should catch any responses that aren't 200/201, parse the error response, then throw a new exception based on that.

**Comment by dcamdupe** [comment]
Can we also add the the comment parameter into refund.

**Comment by eugene-payfurl** [comment]
Fi

> We're missing one item in this. We need to handle errors being returned from the API. Now that we have a consistent error response, we should catch any responses that aren't 200/201, parse the error response, then throw a new exception based on that.

Fixed

**Comment by eugene-payfurl** [comment]
> Can we also add the the comment parameter into refund, see https://linear.app/payfurl/issue/PAY-1149/add-optional-comment-parameter-on-refund-in-sdks

Done by @dcamdupe

**Pull request merged**
